from src.components.code_parser import extract_code_structure
from src.components.doc_generator import generate_explanation

def create_documentation(source_code: str, filename: str = "uploaded_code") -> dict:
    """Complete pipeline to generate documentation."""
    
    # Extract structure
    structure = extract_code_structure(source_code)
    
    # Generate explanation
    explanation = generate_explanation(source_code)
    
    # Create formatted document
    document = f"""
{'='*70}
CODE DOCUMENTATION
{'='*70}

File: {filename}
Lines of Code: {structure['total_lines']}
Functions: {len(structure['functions'])}
Classes: {len(structure['classes'])}

{explanation}

{'='*70}
Generated by AI Documentation Assistant
{'='*70}
"""
    
    return {
        "document": document,
        "structure": structure,
        "explanation": explanation
    }

